### ISSUE TITLE
Needs a progress indicator

### ISSUE THREAD

**Issue by tlhunter** [opentable/request-timeline#24]
There needs to be some visual indicator that the tool is waiting on an AJAX request.

Sometimes a query will take 40 seconds and there's no way of knowing that Timeline is "working".

**Comment by stevenschlansker** [comment]
Does ElasticSearch provide any progress reports back?
We could add a spinner, but I'm not sure we can add any real indication of work happening.

**Comment by tlhunter** [comment]
A spinner would be fine.

**Comment by pennello** [comment]
@stevenschlansker +1 on the spinner idea.
